spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_test?sueUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
#整合mybatis
mybatis:
  # resultType的别名
  type-aliases-package: com.djzhao.mybatis.model
  #  mapper文件位置
  mapper-locations: classpath:mapper/*.xml
